- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy backend dist files web server
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Uncompress Backend
  shell: |
    cd /home/ubuntu/
    tar xvzf artifact.tar.gz -C .
    ls -la
    
- name: Install Node 
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm install --only=dev
- name: Build package
  shell: |
    cd /home/ubuntu/backend
    npm run build
    cat .env
    npm run prestart:prod
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend 
    pm2 stop default
    pm2 start npm --name backend -- start
    
- name: start pm2 for dist/main.js
  become: no
  shell: pm2 start main.js
  args:
    chdir: /home/ubuntu/backend/dist
